### ISSUE TITLE
No formatting for full-width or right aligned images

### ISSUE THREAD

**Issue by ericthelemur** [UWCS/uwcs-dextre#38]
These are options provided in the page authoring system, and result in the classes `full-width` and `right` on the image tag, however no formatting is provided for these classes.
![image](https://user-images.githubusercontent.com/8903016/164733242-6032454c-1bcf-433a-9670-e93f5e748b09.png)

**Comment by joshdavies14** [comment]
My understanding is these are not custom defined classes (i.e. they are added by Wagtail and we are not using custom image functionality for adding in images), and the options in the editor just define the width of the image. For example, if you pick left-aligned or right-aligned, it sets the `width` attribute to 500(?)px, whereas "full-width" is 800(?)px, and then sets the 'height' attribute accordingly. I've never experimented to see if it actually does change the alignment, but that is beyond code we've written. When an image is detected in the "stream field" block, we use the built in Wagtail image tags to load it in (see 'blog/includes/streamfield.html' L34-35) so yeah all these classes are added and defined by Wagtail, and it is doing things in a weird Wagtail way.

If you wanted to do custom things with these classes in the future, you can override them in (IIRC) `static/scss/new/_customised.scss`, but yeah, this is not custom functionality originally :D

**Comment by ericthelemur** [comment]
Ah right, so full-width works fine, left works by default, but right still does not (not that i envision it being used much)

**Comment by joshdavies14** [comment]
For future reference on this: https://docs.wagtail.org/en/stable/topics/images.html#images-embedded-in-rich-text
This explains what happens when you pick each option. Also explains that the classes `left`, `full-width` and `right` should be defined by the developer, so TIL.
On the basis that left-align and full-width already basically do what we want, I'm leaving it with just implementing the `right` class for now.
